# Generated by Django 3.2.3 on 2021-05-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('guid', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('outcome_url', models.URLField()),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'LMS',
            },
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_course_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'LTI courses',
            },
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_user_id', models.CharField(max_length=200)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pl_lti.lms')),
            ],
            options={
                'verbose_name_plural': 'LTI users',
            },
        ),
    ]
