# Generated by Django 3.1.6 on 2021-02-19 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('outcome_url', models.URLField()),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_guid', models.CharField(max_length=200)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pl_lti.lms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_guid', models.CharField(max_length=200)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pl_lti.lms')),
            ],
        ),
    ]
