# Generated by Django 3.1.6 on 2021-02-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('guid', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('outcome_url', models.URLField()),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'lms',
                'verbose_name_plural': 'lms',
            },
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_user_id', models.IntegerField(default=0)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pl_lti.lms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lti user',
                'verbose_name_plural': 'lti users',
                'unique_together': {('lms', 'lms_user_id')},
            },
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_course_id', models.IntegerField(default=0)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pl_lti.lms')),
            ],
            options={
                'verbose_name': 'lti course',
                'verbose_name_plural': 'lti courses',
                'unique_together': {('lms', 'lms_course_id')},
            },
        ),
    ]
