# Generated by Django 3.2.3 on 2021-05-25 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pl_lti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lticourse',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='pl_lti.lms'),
        ),
        migrations.AlterUniqueTogether(
            name='ltiuser',
            unique_together={('lms', 'lms_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='lticourse',
            unique_together={('lms', 'lms_course_id')},
        ),
    ]
