# Generated by Django 3.1.6 on 2021-02-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pl_lti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsm_guid', models.CharField(blank=True, max_length=200, null=True)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms', to='pl_lti.lms')),
                ('pl_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
