# Generated by Django 3.1.6 on 2021-02-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pl_lti', '0002_ltiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuser',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lms', to='pl_lti.lms'),
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsm_guid', models.CharField(blank=True, max_length=200, null=True)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lms', to='pl_lti.lms')),
            ],
        ),
    ]
