# Generated by Django 3.2.3 on 2021-05-23 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('PERSONAL', 'Personal')], default='PUBLIC', max_length=20)),
                ('desc', models.CharField(blank=True, default='Aucune description', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MODEL', 'Model'), ('ACTIVITY', 'Activity'), ('EXERCISE', 'Exercise')], max_length=20)),
                ('desc', models.CharField(blank=True, default='Aucune description', max_length=300)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('DEPRECATED', 'Deprecated'), ('BUGGED', 'Bugged'), ('NOT_TESTED', 'Not Tested')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pl_resources.circle')),
                ('levels', models.ManyToManyField(blank=True, related_name='resources', to='pl_resources.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('DEPRECATED', 'Deprecated'), ('BUGGED', 'Bugged'), ('NOT_TESTED', 'Not Tested')], max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pl_resources.resource')),
            ],
            options={
                'unique_together': {('author', 'number', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='resources', to='pl_resources.Topic'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('GENERIC', 'Generic'), ('MEMBER_ADDED', 'Member Added'), ('MEMBER_REMOVED', 'Member Removed'), ('RESOURCE_CREATED', 'Resource Created'), ('RESOURCE_UPDATED', 'Resource Updated')], default='GENERIC', max_length=20)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pl_resources.circle')),
            ],
        ),
        migrations.AddField(
            model_name='circle',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='circles', to='pl_resources.Level'),
        ),
        migrations.AddField(
            model_name='circle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='circle',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='circles', to='pl_resources.Topic'),
        ),
        migrations.AddField(
            model_name='circle',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pl_resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_viewed_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pl_resources.circle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'circle')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], max_length=20)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pl_resources.circle')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('circle', 'inviter', 'invitee')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pl_resources.version')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='pl_resources.resource')),
            ],
            options={
                'verbose_name_plural': 'Dependencies',
                'unique_together': {('resource', 'dependence')},
            },
        ),
    ]
