# Generated by Django 3.2.3 on 2021-05-25 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pl_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pl_resources.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='resource',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='resources', to='pl_resources.Level'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='resources', to='pl_resources.Topic'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pl_resources.resource'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_viewed_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='circle',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='circles', to='pl_resources.Level'),
        ),
        migrations.AddField(
            model_name='circle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pl_resources.circle'),
        ),
        migrations.AddField(
            model_name='circle',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='circles', to='pl_resources.Topic'),
        ),
        migrations.AddField(
            model_name='circle',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('author', 'number', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='recentview',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'circle')},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('circle', 'inviter', 'invitee')},
        ),
    ]
