# Generated by Django 3.2.3 on 2021-05-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependency',
        ),
    ]
