# Generated by Django 3.2.3 on 2021-05-30 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pl_resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.AddField(
            model_name='circle',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MEMBER_CREATE', 'Member Create'), ('MEMBER_REMOVE', 'Member Remove'), ('RESOURCE_CREATE', 'Resource Create'), ('RESOURCE_STATUS_CHANGE', 'Resource Status Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
