# Generated by Django 3.2 on 2021-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_resources', '0002_auto_20210302_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
