# Generated by Django 3.2.3 on 2021-06-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_resources', '0003_auto_20210530_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='watchers',
        ),
    ]
