# Generated by Django 3.2.3 on 2021-06-21 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pl_resources', '0005_alter_recentview_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('circle', 'invitee')},
        ),
    ]
