# Generated by Django 3.2.5 on 2021-07-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_resources', '0006_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
