# Generated by Django 3.2.5 on 2021-07-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_resources', '0007_delete_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='type',
        ),
    ]
