# Generated by Django 3.1.1 on 2020-09-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'get_latest_by': 'date', 'ordering': ['-date', 'sandbox']},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'get_latest_by': 'date', 'ordering': ['-date', 'sandbox']},
        ),
    ]
