# Generated by Django 3.1b1 on 2020-06-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandbox',
            name='last_usage_poll',
        ),
        migrations.RemoveField(
            model_name='sandbox',
            name='poll_usage_every',
        ),
    ]
