# Generated by Django 3.1b1 on 2020-06-23 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandbox', '0002_auto_20200623_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxusage',
            name='unreachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='bin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='count',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='cpu_count',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='cpu_period',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='cpu_quota',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='cpu_shares',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='libraries',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='memory_ram',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='memory_storage',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='memory_swap',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='process',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='reading_bytes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='reading_io',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='working_dir_device',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='writing_bytes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerspecs',
            name='writing_io',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='cpu_core',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='cpu_freq_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='cpu_freq_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='cpu_logical',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='docker_version',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='memory_ram',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='memory_storage',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='memory_swap',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxspecs',
            name='sandbox_version',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='container',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='cpu_freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='cpu_usage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='memory_ram',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='memory_storage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='memory_swap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='process',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='reading_bytes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='reading_io',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='receiving_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='receiving_packets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='sending_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='sending_packets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='writing_bytes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxusage',
            name='writing_io',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
