# Generated by Django 3.1b1 on 2020-06-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandbox', '0003_auto_20200623_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxusage',
            name='unreachable',
        ),
        migrations.AddField(
            model_name='sandboxusage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sandboxusage',
            name='reached',
            field=models.BooleanField(default=True),
        ),
    ]
