# Generated by Django 3.1b1 on 2020-07-16 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playcourse', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playactivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PL',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('rerollable', models.BooleanField(default=False)),
                ('compilation_data', models.DateField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playactivity.activity')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playcourse.course')),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='PLSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('saved_data', models.JSONField(default=dict)),
                ('seed', models.IntegerField()),
                ('try_count', models.IntegerField(default=0)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.pl')),
            ],
        ),
        migrations.CreateModel(
            name='AnonPLSession',
            fields=[
                ('plsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playexo.plsession')),
                ('user_id', models.UUIDField()),
            ],
            bases=('playexo.plsession',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('answer', models.JSONField()),
                ('seed', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playexo.plsession')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedPLSession',
            fields=[
                ('plsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playexo.plsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('playexo.plsession',),
        ),
    ]
