# Generated by Django 3.1b1 on 2020-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pl',
            old_name='compilation_data',
            new_name='compilation_date',
        ),
        migrations.AddField(
            model_name='pl',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
