# Generated by Django 3.2.3 on 2021-05-25 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pl_sandbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='containerspecs',
            name='sandbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='container_specs', to='pl_sandbox.sandbox'),
        ),
        migrations.AddField(
            model_name='commandresult',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='pl_sandbox.response'),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(fields=['-date'], name='pl_sandbox__date_9a512b_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['-date'], name='pl_sandbox__date_6193f4_idx'),
        ),
    ]
