# Generated by Django 3.1.1 on 2020-09-24 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_sandbox', '0002_auto_20200923_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='url',
            field=models.CharField(max_length=2048, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
