# Generated by Django 3.2 on 2021-04-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_sandbox', '0003_auto_20200924_1204'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='request',
            name='django_sand_date_586f48_idx',
        ),
        migrations.RemoveIndex(
            model_name='usage',
            name='django_sand_date_adf10a_idx',
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['-date'], name='pl_sandbox__date_6193f4_idx'),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(fields=['-date'], name='pl_sandbox__date_9a512b_idx'),
        ),
    ]
