name: Test selfhosted

on:
  push:
    branches: [ "develop-ci" ]
  pull_request:
    branches: [ "develop-ci" ]

jobs:
  test:
    runs-on: self-hosted
    services:
      redis:
        # Docker Hub image
        image: redis:6
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        # Docker Hub image
        image: postgres:13
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_platon
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Python 3.9
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install Sandbox
        run : |
          git clone https://github.com/PremierLangage/sandbox.git
          cd sandbox/
          ./bin/install.sh
          python3 manage.py runserver 7000 &> /dev/null &
          cd ..

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run Migrations
        env:
          DEBUG: true
        run: |
          python3 manage.py waitdb
          python3 manage.py migrate
          python3 manage.py createdefaults

      - name: Run Tests
        env:
          DEBUG: true
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
